version: '3.2'

services:

  postgres_db:
    image: postgres:latest
    container_name: subscription_db_container
    restart: always
    environment:
      PGPORT: 5432
      POSTGRES_DB: subscription_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - ./data/postgres:/data
    ports:
      - "5432:5432"
